project: 
  type: website
  output-dir: docs/
  render:
  - "*.qmd"

execute:
  freeze: true

website:
  bread-crumbs: false
  open-graph: true
  page-navigation: false 
  title: "EON Summer School 2025"
  site-url: https://earth-observation-network.github.io/EON2025
  repo-url: https://github.com/earth-observation-network/EON2025
  repo-actions: [edit, issue]
  search: 
    location: navbar
    type: textbox
  page-footer: "Earth Observation Network Harz Summer School (2025)" 
  navbar:
    logo: /images/logooil.jpg
  sidebar:
    # logo: /images/logo.jpg
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:
      - section: "Welcome"
        contents:
          - index.qmd
      - text: "---"
      - section: "Block 1: Reference Data Collection"
        contents: 
          - block1_magdon/01_TrainingDataCollection.qmd
          - block1_magdon/02_ValidationDataCollection.qmd
      - text: "---"
      - section: "Block 2: Processing of 3D LiDAR data to assess forest structure"
        contents: 
          - block2_bas_dob/lidar_forest_structure.qmd
      - text: "---"
      - section: "Block 3: Machine Learning"
        contents:
          - ml_session/ML_AOA.qmd
      - text: "---"
      - section: "Block 4: Microclimate Data Retrieval & Spatial Data Interpolation"
        contents:
          - block4_5/mc_2025_0.qmd
          - block4_5/mc_2025_1.qmd
          - block4_5/mc_2025_microclimate_viewer_merged.qmd
          - block4_5/mc_2025_tec.qmd
          - block4_5/mc_2025_data.qmd
      - text: "---"
      - section: "Block 5: Spatial patterns"
        contents:
          - block6/index.qmd

format:
  html:
    theme:
      light: lumen
      dark: [lumen, css/theme-dark.scss]
    code-background: true
    code-copy: true
    css: css/styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
